version: '1.0'

services:
  server:
    build:
      context: ./back-end/
    command: npm run dev
    container_name: server
    volumes:
      - ./back-end/:/usr/app
      - /usr/app/node_modules
    env_file: .env
    environment: 
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "4000:4000"
  client:
    build:
      context: ./front-end/
    command: npm start
    container_name: client
    volumes:
      - ./front-end/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"